language: php

php:
  - 5.6
  - 7.0.22
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_cli_test;" -uroot

script:
  - OMEKA_DB_USER=root ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no
