language: php
services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

env:
    - OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.6.1/omeka-2.6.1.zip
    - OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.7.1/omeka-2.7.1.zip

matrix:
  exclude:
    - php: 7.3
      env: OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.6.1/omeka-2.6.1.zip
    - php: 7.4
      env: OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.6.1/omeka-2.6.1.zip

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_cli_test;" -uroot

script:
  - OMEKA_DB_USER=root ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no
