language: php
services:
  - mysql

php:
  - 5.6
  - 7.0.22
  - 7.1
  - 7.2

env:
    - OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.5.1/omeka-2.5.1.zip
    - OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.6/omeka-2.6.zip
    - OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.6.1/omeka-2.6.1.zip

matrix:
  exclude:
    - php: 7.2
      env: OMEKA_ZIP_PATH=https://github.com/omeka/Omeka/releases/download/v2.5.1/omeka-2.5.1.zip

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_cli_test;" -uroot

script:
  - OMEKA_DB_USER=root ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no
